# This is a basic workflow to help you get started with Actions

name: GermsTore

# Contrôle le moment où le flux de vente sera exécuté
on:
  # Déclenche le le flux de vente sur des événements de push ou pull request mais uniquement pour la branche "principale"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Vous permet d'exécuter ce le flux de vente manuellement à partir de l'onglet Actions
  workflow_dispatch:

# Une exécution de workflow est composée d'une ou plusieurs tâches pouvant s'exécuter séquentiellement ou en parallèle.
jobs:
  # son flux de travail contient un seul travail appelé "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a sin
